# Generated by Django 3.2.6 on 2021-09-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='audio',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='has_audio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
